# fly.toml app configuration file generated for tcq on 2023-05-18T14:12:28+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tcq"
primary_region = "ewr"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[env]
DATABASE_PATH = "/data/db.sqlite3"
BASE_URL = "https://tcq.fly.dev"

[mounts]
source = "sqlite"
destination = "/data"
